INSERT INTO `autor`(`nome`) VALUES ('Abel Neves'),
('Abha Dawesar'),
('Afonso Cruz'),
('Afonso Reis Cabral'),
('Agatha Christie'),
('Agustín Sánchez Vidal'),
('Albert Camus'),
('Albrecht Hagemann'),
('Aldous Huxley'),
('Alessandro Baricco'),
('Alexander Pushkin'),
('Alexandra Bullen'),
('Alexandre Borges'),
('Alice Hoffman'),
('Alice Kuipers'),
('Allan e Barbara Pease'),
('Alphonse Daudet'),
('Alyson Noël'),
('Amaya Ascunce'),
('Amitav Ghosh'),
('Amos Oz'),
('Ana R. Bravo'),
('Ana Veloso'),
('Ana Vicente Ferreira'),
('Andrea Vitali'),
('André Brink'),
('Andrew Davidson'),
('Andy Weir'),
('Ángela Becerra'),
('Anita Shreve'),
('Anna Elliott'),
('Anne Bishop'),
('Anne McCaffrey'),
('Anthony Bourke & John Rendall'),
('Anthony Burgess'),
('Antoine de Saint-Exupéry'),
('Antonio Garrido'),
('Antonio Skármeta'),
('Aravind Adiga'),
('Arthur Conan Doyle'),
('Arturo Pérez-Reverte'),
('Audrey Niffenegger'),
('Barbara Bretton'),
('Barbara Kyle'),
('Ben Sherwood'),
('Bernhard Schlink'),
('Bill Bryson'),
('Boris Starling'),
('Bram Stoker'),
('Brian K. Vaughan'),
('Bruce Holland Rogers'),
('Brunonia Barry'),
('C.J. Sansom'),
('C.S. Lewis'),
('C.S. Richardson'),
('Camilla Läckberg'),
('Carina Portugal'),
('Carlos María Domínguez'),
('Carlos Ruiz Zafón'),
('Cassandra Clare'),
('Catarina Coelho'),
('Catarina Pereira Araújo'),
('Catherine Anderson'),
('Cecelia Ahern'),
('Célia Correia Loureiro'),
('Charlaine Harris'),
('Charles Dickens'),
('Charles Frazier'),
('Charles Martin'),
('Charles R. Cross'),
('Charlotte Brontë'),
('Charmian Hussey'),
('Chico Buarque'),
('Chimamanda Ngozi Adichie'),
('Chris Cleave'),
('Christine Feehan'),
('Christopher Moore'),
('Christopher Priest'),
('Chuck Palahniuk'),
('Colleen McCullough'),
('Colum McCann'),
('Cormac McCarthy'),
('Cristina López Barrio'),
('Dacre Stoker e Ian Holt'),
('Dan Brown'),
('Daniel Pennac'),
('Daniel Silva'),
('Danny Scheinmann'),
('Daphne du Maurier'),
('Daphne Kalotay'),
('Dave Eggers'),
('David Allen'),
('David Hewson'),
('David Lodge'),
('David Machado'),
('David Mitchell'),
('David Nicholls'),
('David Safier'),
('David Soares'),
('David Wroblewski'),
('Dean Koontz'),
('Debbie Macomber'),
('Deborah Smith'),
('Diana de Cadaval'),
('Diana Gabaldon'),
('Diane Haeger'),
('Diane Setterfield'),
('Don DeLillo'),
('Donna Tartt'),
('Donna Woolfolk Cross'),
('Dorothy Koomson'),
('Dulce Maria Cardoso'),
('Eça de Queiroz'),
('Eduardo Madeira'),
('Eileen Goudge'),
('Elise Blackwell'),
('Elizabeth Adler'),
('Elizabeth Chadwick'),
('Elizabeth Edmondson'),
('Elizabeth Gaskell'),
('Elizabeth Hickey'),
('Elizabeth Hoyt'),
('Elizabeth Kostova'),
('Emily Brontë'),
('Emily Giffin'),
('Emma Darwin'),
('Emmanuel Jal'),
('Emylia Hall'),
('Erik Qualman'),
('Ernest Hemingway'),
('Evgueni Zami­a­tine'),
('F. Scott Fitzgerald
('Fabio Geda'),
('Fábio Ventura'),
('Fabio Volo'),
('Fédor Dostoievski'),
('Félix J. Palma'),
('Fernando Alvim'),
('Filomena Marona Beja'),
('Florencia Bonelli'),
('Francisco Dionísio'),
('Francisco José Viegas'),
('Frank Herbert'),
('Frank McCourt'),
('Frank Ronan'),
('Franz Kafka'),
('F.X. Toole'),
('Gabriel García Márquez'),
('Gary Jennings'),
('Geoff Ryman'),
('George MacDonald Fraser'),
('George Orwell'),
('George R.R. Martin'),
('Giani Stuparich'),
('Gillian Flynn'),
('Gonçalo M. Tavares'),
('Graeme Simsion'),
('Guillaume Musso'),
('Guil­lermo Cabrera Infante'),
('Guillermo Martínez'),
('Guy Gavriel Kay'),
('H.G. Wells'),
('Hannah Richell'),
('Harlan Coben'),
('Harper Lee'),
('Haruki Murakami'),
('Hélder Macedo'),
('Helena Sacadura Cabral'),
('Helene Hanff'),
('Henry James'),
('Henry Miller'),
('Herman Hesse'),
('Hilary Mantel'),
('Hugh Howey'),
('Hugh Laurie'),
('Ian Fleming'),
('Ian McEwan'),
('Ignacio del Valle'),
('Ildefonso Falcones'),
('Ilona Andrews'),
('Inês Botelho'),
('Inês Pedrosa'),
('Isabel Allende'),
('Isabel Stilwell'),
('Italo Calvino'),
('J.D. Robb'),
('J.K. Rowling'),
('J.M. Coetzee'),
('J.M.G. Le Clézio'),
('J.P. Simões'),
('J.R. Moehringer'),
('J.R. Ward'),
('J.R.R. Tolkien'),
('Jack & Holman Wang'),
('Jacqueline Carey'),
('Jacqueline Susann'),
('Jacquelyn Mitchard'),
('Jacques Bonnet'),
('James Frey e Nils Johnson-Shelton'),
('James Patterson'),
('Jane Austen'),
('Jane Harris'),
('Janet Evanovich'),
('Janet Paisley'),
('Javier González'),
('Jeannette Walls'),
('Jean-Pierre Luminet'),
('Jeanne Kalogridis'),
('Jeffrey Brown'),
('Jennie Rooney'),
('Jennifer Donnelly'),
('Jennifer Egan'),
('Jenny Tomlin'),
('Jessica Brockmole'),
('Jill Mansell'),
('Joanne Harris'),
('Joann Sfar'),
('João Barreiros'),
('João Bonifácio'),
('João Céu e Silva'),
('João Ferreira'),
('João Pedro Marques'),
('João Tordo'),
('Joaquim Magalhães de Castro'),
('Jo Baker'),
('Jodi Picoult'),
('John Boyne'),
('John Collier'),
('John Freeman'),
('John Harding'),
('John Le Carré'),
('John O’Hara'),
('John Scalzi'),
('John Steinbeck'),
('John Williams'),
('Jojo Moyes'),
('Jon Krakauer'),
('Jorge Amado'),
('Jorge Candeias'),
('Jorge Luis Borges'),
('José Gil'),
('José Luís Peixoto'),
('Joseph Conrad'),
('Joseph Pearce'),
('José de Oliveira Cosme'),
('José Rodrigues dos Santos'),
('José Saramago'),
('Juan José Millás'),
('Julia Glass'),
('Julia Navarro'),
('Julia Quinn'),
('Juliet Marillier'),
('Júlio Conrado'),
('Junot Díaz'),
('Justin Cronin'),

Read more: http://www.estantedelivros.com/autores#ixzz3r8q1X2aL

Read more: http://www.estantedelivros.com/autores#ixzz3r8prOFuu

Read more: http://www.estantedelivros.com/autores#ixzz3r8pgbh4X

Read more: http://www.estantedelivros.com/autores#ixzz3r8pUCNGS

Read more: http://www.estantedelivros.com/autores#ixzz3r8pGQDme

Read more: http://www.estantedelivros.com/autores#ixzz3r8fZstbS

Read more: http://www.estantedelivros.com/autores#ixzz3r8fAlxcl

Read more: http://www.estantedelivros.com/autores#ixzz3r8eo8wvG

Read more: http://www.estantedelivros.com/autores#ixzz3r8eeoJON

Read more: http://www.estantedelivros.com/autores#ixzz3r8dl0zsw