INSERT INTO `categoria`(`nome`) VALUES
('Artes'),
('Autoajuda'),
('Biografia e memórias'),
('Educação'),
('Ficção científica e fantasia'),
('Ficção e literatura'),
('Gastronomia'),
('História'),
('Humor'),
('Infantil'),
('Mistério e suspense'),
('Negócios'),
('Poesia'),
('Psicologia'),
('Religião e espiritualidade'),
('Romance');

INSERT INTO `subcategoria`(`nome`) VALUES
/*Artes*/
('Geral'),
('Americano'),
('Artistas autônomos'),
('Assuntos e temas'),
('Coleções, catálogos, exposições'),
('Filmes e vídeo'),
('História'),
('Técnicas'),
/*Autoajuda*/
('Geral'),
('Abuso de substâncias e vícios'),
('Controle da raiva'),
('Crescimnto pessoal'),
('Envelhecimento'),
('Gerenciamento de equipe'),
('Gerenciamento do stress'),
('Morte, tristeza, luto'),
('Motivacional e inspirador'),
('Sonhos'),
/*Biografia*/
('Geral'),
('Artistas, arquitetos, fotógrafos'),
('Aventureiros e exploradores'),
('Ciência e Tecnologia'),
('Cientistas sociais e psicólogos'),
('Compositores e músicos'),
('Criminosos e foras-da-lei'),
('Entretenimento e artes cênicas'),
('Esportes'),
('Histórico'),
('Literário'),
('Medicina'),
('Memórias pessoais'),
('Militar'),
('Mulheres'),
('Negócios'),
('Político'),
('Presidentes e chefes de Estado'),
('Realeza'),
('Religioso'),
/*Educação*/
('Geral'),
('Aconselhamento'),
('Administração'),
('Educação especial'),
('Inglês'),
('Métodos e materias de ensino'),
('Política e reforma educacional'),
('Referência'),
/*Ficção científica*/
('Geral'),
('Alta tecnologia'),
('Aventura'),
('Contemporâneo'),
('Contos'),
('Épico'),
('Histórico'),
('Militar'),
('Paranormal'),
('Space Opera'),
('Vida Urbana'),
/*Ficção*/
('Geral'),
('Ação e Aventura'),
('Afro-americano'),
('Antologias (vários autores)'),
('Biográfico'),
('Clássicos'),
('Contos (único autor)'),
('Contos de fada, folclóricos, lendas e mitologia'),
('Crime'),
('Cristão'),
('Erótico'),
('Espionagem'),
('Fantasia'),
('Ficção científica'),
('Guerra e militares'),
('História alternativa'),
('Histórico'),
('Humorístico'),
('Jurídico'),
('Maioridade'),
('Medicina'),
('Mistério e detetive'),
('Mulheres contemporâneas'),
('Oculto e sobrenatural'),
('Político'),
('Psicológico'),
('Religioso'),
('Romances'),
('Sagas'),
('Suspense'),
('Tecnológico'),
('Terror'),
('Thrillers'),
('Vida familiar'),
('Vida urbana'),
/*Gastronomia*/
('Geral'),
('Bebidas'),
('História'),
('Ingredientes específicos'),
('Métodos'),
('Pratos'),
('Regional e étnico'),
('Saúde e cura'),
/*História*/
('Geral'),
('África'),
('América Latina'),
('Américas'),
('Antiguidade'),
('Ásia'),
('Canadá'),
('Caribe e Índias Ocidentais'),
('Civilização'),
('Estados Unidos'),
('Europa'),
('Medieval'),
('Militar'),
('Moderno'),
('Mundo'),
('Oriente Médio'),
/*Humor*/
('Geral'),
('Forma'),
('Tópico'),
/*Infantil*/
('Geral'),
('Ação e Aventura'),
('Animais'),
('Ciência e Natureza'),
('Clássicos'),
('Contos de Fadas e folclore'),
('Esportes e lazer'),
('Família'),
('História'),
('Histórias de mistério e detetive'),
('Jogos e atividades'),
('Lendas, mitos e fábulas'),
('Questões sociais'),
('Referência'),
('Religião'),
/*Mistério*/
('Geral'),
('Crime real'),
('Histórico'),
('Procedimento policial'),
('Suspense'),
/*Negócios*/
('Geral'),
('Comércio eletrônico'),
('Comunicação corporativa'),
('Condições econômicas'),
('Contabilidade'),
('Desenvolvimento'),
('Economia'),
('Empreendedorismo'),
('Ética empresarial'),
('Finanças'),
('Finanças pessoais'),
('Gerenciamento'),
('Governo e Negócios'),
('História econômica'),
('Indústrias'),
('Internacional'),
('Liderança'),
('Marketing'),
('Motivacional'),
('Negociação'),
('Pequenas empresas'),
('Planejamento estratégico'),
('Profissões'),
('Publicidade e promoção'),
('Recursos humanos'),
('Seguros'),
('Tributação'),
/*Poesia*/
('Geral'),
('Americano'),
('Caribenho e latino-americano'),
/*Psicologia*/
('Geral'),
('Avaliação, teste e análise'),
('Capacidade criativa'),
('Desenvolvimento'),
('Educação e treinamento'),
('Movimentos'),
('Psicologia social'),
('Psicopatologia'),
('Psicoterapia'),
('Relações interpessoais'),
('Sexualidade humana'),
/*Religião*/
('Geral'),
('Ateísmo'),
('Biografia bíblica'),
('Budismo'),
('Comentário bíblico'),
('Cristianismo'),
('Crítica e interpretação'),
('Educação Cristão'),
('Espiritualidade'),
('Estudos bíblicos'),
('Ética'),
('Feriados'),
('Hinduísmo'),
('Igreja Cristão'),
('Islamismo'),
('Judaísmo'),
('Livros de orações'),
('Meditações bíblicas'),
('Ministério Cristão'),
('Práticas e rituais cristãos'),
('Referência bíblica'),
('Sermões'),
('Sexualidade'),
('Teologia'),
('Teologia cristã'),
('Vida cristã'),
/*Romance*/
('Geral'),
('Contemporâneo'),
('Fantasia'),
('Histórico'),
('Paranormal'),
('Suspense');